### ISSUE TITLE
Include performance tracking

### ISSUE THREAD

**Issue by Requinard** [Requinard/reggie#10]
- [x] Include prometheus URLs in Django
- [x] Set up custom prometheus docker service
- [x] Set up grafana service
- [ ] Create grafana dashboard to show data
- [ ] Include grafana sub-url in nginx config

**Comment by Requinard** [comment]
b18ab913bea4b731ba5ef99020a86588ec142a1f
